# Generated by Django 3.2.25 on 2024-04-22 05:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Company_Staff', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='saleorder',
            name='convert_to_invoice',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Company_Staff.invoice'),
        ),
        migrations.AddField(
            model_name='saleorder',
            name='convert_to_recurringinvoice',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Company_Staff.recurringinvoice'),
        ),
    ]
