# Generated by Django 3.2.25 on 2024-04-22 06:59

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('Register_Login', '0017_alter_trialperiod_interested_in_buying'),
        ('Company_Staff', '0002_auto_20240422_0502'),
    ]

    operations = [
        migrations.AddField(
            model_name='retainerinvoice',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='retainerinvoice',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='retainer_created', to='Register_Login.logindetails'),
        ),
        migrations.AddField(
            model_name='retainerinvoice',
            name='modified_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='retainerinvoice',
            name='modified_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='retainer_modified', to='Register_Login.logindetails'),
        ),
    ]
