# Generated by Django 3.2.25 on 2024-05-03 10:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Register_Login', '0017_alter_trialperiod_interested_in_buying'),
        ('Company_Staff', '0003_auto_20240422_0659'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bill_history',
            old_name='Bill',
            new_name='bills',
        ),
        migrations.RenameField(
            model_name='bill_history',
            old_name='Login_Details',
            new_name='login_details',
        ),
        migrations.RemoveField(
            model_name='bill_history',
            name='Action',
        ),
        migrations.RemoveField(
            model_name='bill_history',
            name='Company',
        ),
        migrations.RemoveField(
            model_name='bill_history',
            name='Date',
        ),
        migrations.RemoveField(
            model_name='billitems',
            name='Discount',
        ),
        migrations.RemoveField(
            model_name='billitems',
            name='HSN',
        ),
        migrations.RemoveField(
            model_name='billitems',
            name='Items',
        ),
        migrations.RemoveField(
            model_name='billitems',
            name='Price',
        ),
        migrations.RemoveField(
            model_name='billitems',
            name='Quantity',
        ),
        migrations.RemoveField(
            model_name='billitems',
            name='Tax_Rate',
        ),
        migrations.RemoveField(
            model_name='billitems',
            name='Total',
        ),
        migrations.AddField(
            model_name='bill',
            name='pattern',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='bill_history',
            name='action',
            field=models.CharField(choices=[('Created', 'Created'), ('Edited', 'Edited')], max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='bill_history',
            name='company',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Register_Login.companydetails'),
        ),
        migrations.AddField(
            model_name='bill_history',
            name='date',
            field=models.DateField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='billitems',
            name='bal_qty',
            field=models.PositiveBigIntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='billitems',
            name='discount',
            field=models.PositiveBigIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='billitems',
            name='item_hsn',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='billitems',
            name='item_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Company_Staff.items'),
        ),
        migrations.AddField(
            model_name='billitems',
            name='item_name',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='billitems',
            name='price',
            field=models.PositiveBigIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='billitems',
            name='qty',
            field=models.PositiveBigIntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='billitems',
            name='taxGST',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='billitems',
            name='taxIGST',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='billitems',
            name='total',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='billitems',
            name='total_qty',
            field=models.PositiveBigIntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='billitems',
            name='Bills',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Company_Staff.bill'),
        ),
    ]
