# Generated by Django 3.2.25 on 2024-05-08 09:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Company_Staff', '0004_auto_20240503_1050'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historysalarydetails',
            name='action',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='historysalarydetails',
            name='date',
            field=models.DateField(auto_now=True, null=True),
        ),
    ]
